import{DATA_KEY,BACKUP_KEY,EXPENSE_DEFAULTS,INCOME_DEFAULTS}from"./constants.js";import{uid}from"./format.js";
const cats=(arr,type)=>arr.map(([id,name,emoji,color])=>({id,name,emoji,color,type,system:true,archived:false}));
export function blank(){return{schema:6,userName:"Christian",theme:"midnight",privacy:false,accounts:[{id:uid(),name:"Efectivo",type:"cash",openingBalance:0},{id:uid(),name:"Banco",type:"bank",openingBalance:0},{id:uid(),name:"Ahorros",type:"savings",openingBalance:0}],transactions:[],budgets:[],goals:[],categories:[...cats(EXPENSE_DEFAULTS,"expense"),...cats(INCOME_DEFAULTS,"income")],settings:{updateReminders:true}}}
const normType=t=>t==="gasto"?"expense":t==="ingreso"?"income":t;
export function normalize(raw){const d={...blank(),...(raw||{})};d.accounts=(d.accounts||[]).map(a=>({id:a.id||uid(),name:a.name||"Cuenta",type:a.type||"bank",openingBalance:Number(a.openingBalance??a.balance??0),creditLimit:Number(a.creditLimit||0),statementDay:Number(a.statementDay||0),dueDay:Number(a.dueDay||0),minimumPayment:Number(a.minimumPayment||0),noInterestPayment:Number(a.noInterestPayment||0)}));
const existing=Array.isArray(d.categories)?d.categories:[];const defaults=blank().categories;const byId=new Map(existing.map(c=>[c.id,c]));d.categories=[...defaults.map(c=>({...c,...byId.get(c.id)})),...existing.filter(c=>!defaults.some(x=>x.id===c.id))].map(c=>({...c,id:c.id||uid(),type:c.type||"expense",name:c.name||"Categoría",emoji:c.emoji||"•",color:c.color||"#8395a7",system:Boolean(c.system),archived:Boolean(c.archived)}));
const findCat=(name,type)=>d.categories.find(c=>c.type===type&&c.name.toLowerCase()===String(name||"").toLowerCase())||d.categories.find(c=>c.type===type&&c.id.endsWith("other"));d.transactions=(d.transactions||[]).map(t=>{const type=normType(t.type)||"expense",cat=d.categories.find(c=>c.id===t.categoryId)||findCat(t.category,type);return{id:t.id||uid(),type,amount:Number(t.amount||0),categoryId:cat?.id||null,category:cat?.name||t.category||"",accountId:t.accountId||t.account||null,destinationId:t.destinationId||null,date:t.date||new Date().toISOString().slice(0,10),note:t.note||"",createdAt:t.createdAt||Date.now()}});
d.budgets=(d.budgets||[]).map(b=>{const c=d.categories.find(x=>x.id===b.categoryId)||findCat(b.category,"expense");return{id:b.id||uid(),categoryId:c?.id||null,limit:Number(b.limit||0)}});d.goals=(d.goals||[]).map(g=>({id:g.id||uid(),name:g.name||"Meta",target:Number(g.target||0),saved:Number(g.saved||0)}));d.schema=6;return d}
export function load(){try{const text=localStorage.getItem(DATA_KEY);if(text)return normalize(JSON.parse(text))}catch(e){console.warn(e)}return blank()}
export function persist(data){const old=localStorage.getItem(DATA_KEY);if(old)localStorage.setItem(BACKUP_KEY,old);const text=JSON.stringify(data);localStorage.setItem(DATA_KEY,text);if(localStorage.getItem(DATA_KEY)!==text)throw Error("No se pudo verificar el guardado")}
export function exportData(data){return new Blob([JSON.stringify({app:"ConFin",version:"6.0.0",exportedAt:new Date().toISOString(),data},null,2)],{type:"application/json"})}
export function importData(obj){return normalize(obj?.data||obj)}